namespace CCVTAC.Console.PostProcessing

open System
open System.Collections.Generic
open System.Text.Json.Serialization

type VideoMetadata = {
    [<property: JsonPropertyName("id")>] Id: string
    [<property: JsonPropertyName("title")>] Title: string
    [<property: JsonPropertyName("thumbnail")>] Thumbnail: string
    [<property: JsonPropertyName("description")>] Description: string
    [<property: JsonPropertyName("channel_id")>] ChannelId: string
    [<property: JsonPropertyName("channel_url")>] ChannelUrl: string
    [<property: JsonPropertyName("duration")>] Duration: Nullable<int>
    [<property: JsonPropertyName("view_count")>] ViewCount: Nullable<int>
    [<property: JsonPropertyName("age_limit")>] AgeLimit: Nullable<int>
    [<property: JsonPropertyName("webpage_url")>] WebpageUrl: string
    [<property: JsonPropertyName("categories")>] Categories: IReadOnlyList<string>
    [<property: JsonPropertyName("tags")>] Tags: IReadOnlyList<string>
    [<property: JsonPropertyName("playable_in_embed")>] PlayableInEmbed: Nullable<bool>
    [<property: JsonPropertyName("live_status")>] LiveStatus: string
    [<property: JsonPropertyName("release_timestamp")>] ReleaseTimestamp: Nullable<int>
    [<property: JsonPropertyName("_format_sort_fields")>] FormatSortFields: IReadOnlyList<string>
    [<property: JsonPropertyName("album")>] Album: string
    [<property: JsonPropertyName("artist")>] Artist: string
    [<property: JsonPropertyName("track")>] Track: string
    [<property: JsonPropertyName("comment_count")>] CommentCount: Nullable<int>
    [<property: JsonPropertyName("like_count")>] LikeCount: Nullable<int>
    [<property: JsonPropertyName("channel")>] Channel: string
    [<property: JsonPropertyName("channel_follower_count")>] ChannelFollowerCount: Nullable<int>
    [<property: JsonPropertyName("channel_is_verified")>] ChannelIsVerified: Nullable<bool>
    [<property: JsonPropertyName("uploader")>] Uploader: string
    [<property: JsonPropertyName("uploader_id")>] UploaderId: string
    [<property: JsonPropertyName("uploader_url")>] UploaderUrl: string
    [<property: JsonPropertyName("upload_date")>] UploadDate: string
    [<property: JsonPropertyName("creator")>] Creator: string
    [<property: JsonPropertyName("alt_title")>] AltTitle: string
    [<property: JsonPropertyName("availability")>] Availability: string
    [<property: JsonPropertyName("webpage_url_basename")>] WebpageUrlBasename: string
    [<property: JsonPropertyName("webpage_url_domain")>] WebpageUrlDomain: string
    [<property: JsonPropertyName("extractor")>] Extractor: string
    [<property: JsonPropertyName("extractor_key")>] ExtractorKey: string
    [<property: JsonPropertyName("playlist_count")>] PlaylistCount: Nullable<int>
    [<property: JsonPropertyName("playlist")>] Playlist: string
    [<property: JsonPropertyName("playlist_id")>] PlaylistId: string
    [<property: JsonPropertyName("playlist_title")>] PlaylistTitle: string
    [<property: JsonPropertyName("n_entries")>] NEntries: Nullable<int>
    [<property: JsonPropertyName("playlist_index")>] PlaylistIndex: Nullable<uint32>
    [<property: JsonPropertyName("display_id")>] DisplayId: string
    [<property: JsonPropertyName("fulltitle")>] Fulltitle: string
    [<property: JsonPropertyName("duration_string")>] DurationString: string
    [<property: JsonPropertyName("release_date")>] ReleaseDate: string
    [<property: JsonPropertyName("release_year")>] ReleaseYear: Nullable<uint32>
    [<property: JsonPropertyName("is_live")>] IsLive: Nullable<bool>
    [<property: JsonPropertyName("was_live")>] WasLive: Nullable<bool>
    [<property: JsonPropertyName("epoch")>] Epoch: Nullable<int>
    [<property: JsonPropertyName("asr")>] Asr: Nullable<int>
    [<property: JsonPropertyName("filesize")>] Filesize: Nullable<int>
    [<property: JsonPropertyName("format_id")>] FormatId: string
    [<property: JsonPropertyName("format_note")>] FormatNote: string
    [<property: JsonPropertyName("source_preference")>] SourcePreference: Nullable<int>
    [<property: JsonPropertyName("audio_channels")>] AudioChannels: Nullable<int>
    [<property: JsonPropertyName("quality")>] Quality: Nullable<double>
    [<property: JsonPropertyName("has_drm")>] HasDrm: Nullable<bool>
    [<property: JsonPropertyName("tbr")>] Tbr: Nullable<double>
    [<property: JsonPropertyName("url")>] Url: string
    [<property: JsonPropertyName("language_preference")>] LanguagePreference: Nullable<int>
    [<property: JsonPropertyName("ext")>] Ext: string
    [<property: JsonPropertyName("vcodec")>] Vcodec: string
    [<property: JsonPropertyName("acodec")>] Acodec: string
    [<property: JsonPropertyName("container")>] Container: string
    [<property: JsonPropertyName("protocol")>] Protocol: string
    [<property: JsonPropertyName("resolution")>] Resolution: string
    [<property: JsonPropertyName("audio_ext")>] AudioExt: string
    [<property: JsonPropertyName("video_ext")>] VideoExt: string
    [<property: JsonPropertyName("vbr")>] Vbr: Nullable<int>
    [<property: JsonPropertyName("abr")>] Abr: Nullable<double>
    [<property: JsonPropertyName("format")>] Format: string
    [<property: JsonPropertyName("_type")>] Type: string }
