using System.Text.Json.Serialization;

namespace CCVTAC.Console.PostProcessing;

/// <summary>
/// Represents the data containing the JSON file downloaded alongside the video.
/// </summary>
public readonly record struct VideoMetadata(
    [property: JsonPropertyName("id")] string Id,
    [property: JsonPropertyName("title")] string Title,
    [property: JsonPropertyName("thumbnail")] string Thumbnail,
    [property: JsonPropertyName("description")] string Description,
    [property: JsonPropertyName("channel_id")] string ChannelId,
    [property: JsonPropertyName("channel_url")] string ChannelUrl,
    [property: JsonPropertyName("duration")] int? Duration,
    [property: JsonPropertyName("view_count")] int? ViewCount,
    [property: JsonPropertyName("age_limit")] int? AgeLimit,
    [property: JsonPropertyName("webpage_url")] string WebpageUrl,
    [property: JsonPropertyName("categories")] IReadOnlyList<string> Categories,
    [property: JsonPropertyName("tags")] IReadOnlyList<string> Tags,
    [property: JsonPropertyName("playable_in_embed")] bool? PlayableInEmbed,
    [property: JsonPropertyName("live_status")] string LiveStatus,
    [property: JsonPropertyName("release_timestamp")] int? ReleaseTimestamp,
    [property: JsonPropertyName("_format_sort_fields")] IReadOnlyList<string> FormatSortFields,
    [property: JsonPropertyName("album")] string Album,
    [property: JsonPropertyName("artist")] string Artist,
    [property: JsonPropertyName("track")] string Track,
    [property: JsonPropertyName("comment_count")] int? CommentCount,
    [property: JsonPropertyName("like_count")] int? LikeCount,
    [property: JsonPropertyName("channel")] string Channel,
    [property: JsonPropertyName("channel_follower_count")] int? ChannelFollowerCount,
    [property: JsonPropertyName("channel_is_verified")] bool? ChannelIsVerified,
    [property: JsonPropertyName("uploader")] string Uploader,
    [property: JsonPropertyName("uploader_id")] string UploaderId,
    [property: JsonPropertyName("uploader_url")] string UploaderUrl,
    [property: JsonPropertyName("upload_date")] string UploadDate,
    [property: JsonPropertyName("creator")] string Creator,
    [property: JsonPropertyName("alt_title")] string AltTitle,
    [property: JsonPropertyName("availability")] string Availability,
    [property: JsonPropertyName("webpage_url_basename")] string WebpageUrlBasename,
    [property: JsonPropertyName("webpage_url_domain")] string WebpageUrlDomain,
    [property: JsonPropertyName("extractor")] string Extractor,
    [property: JsonPropertyName("extractor_key")] string ExtractorKey,
    [property: JsonPropertyName("playlist_count")] int? PlaylistCount,
    [property: JsonPropertyName("playlist")] string Playlist,
    [property: JsonPropertyName("playlist_id")] string PlaylistId,
    [property: JsonPropertyName("playlist_title")] string PlaylistTitle,
    [property: JsonPropertyName("n_entries")] int? NEntries,
    [property: JsonPropertyName("playlist_index")] uint? PlaylistIndex,
    [property: JsonPropertyName("display_id")] string DisplayId,
    [property: JsonPropertyName("fulltitle")] string Fulltitle,
    [property: JsonPropertyName("duration_string")] string DurationString,
    [property: JsonPropertyName("release_date")] string ReleaseDate,
    [property: JsonPropertyName("release_year")] uint? ReleaseYear,
    [property: JsonPropertyName("is_live")] bool? IsLive,
    [property: JsonPropertyName("was_live")] bool? WasLive,
    [property: JsonPropertyName("epoch")] int? Epoch,
    [property: JsonPropertyName("asr")] int? Asr,
    [property: JsonPropertyName("filesize")] int? Filesize,
    [property: JsonPropertyName("format_id")] string FormatId,
    [property: JsonPropertyName("format_note")] string FormatNote,
    [property: JsonPropertyName("source_preference")] int? SourcePreference,
    [property: JsonPropertyName("audio_channels")] int? AudioChannels,
    [property: JsonPropertyName("quality")] double? Quality,
    [property: JsonPropertyName("has_drm")] bool? HasDrm,
    [property: JsonPropertyName("tbr")] double? Tbr,
    [property: JsonPropertyName("url")] string Url,
    [property: JsonPropertyName("language_preference")] int? LanguagePreference,
    [property: JsonPropertyName("ext")] string Ext,
    [property: JsonPropertyName("vcodec")] string Vcodec,
    [property: JsonPropertyName("acodec")] string Acodec,
    [property: JsonPropertyName("container")] string Container,
    [property: JsonPropertyName("protocol")] string Protocol,
    [property: JsonPropertyName("resolution")] string Resolution,
    [property: JsonPropertyName("audio_ext")] string AudioExt,
    [property: JsonPropertyName("video_ext")] string VideoExt,
    [property: JsonPropertyName("vbr")] int? Vbr,
    [property: JsonPropertyName("abr")] double? Abr,
    [property: JsonPropertyName("format")] string Format,
    [property: JsonPropertyName("_type")] string Type
);
